kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: utility-server
  namespace: iankwatts-tools
  resourceVersion: '104856850'
spec:
  nodeSelector: null
  source:
    type: Git
    git:
      uri: https://github.com/IanKWatts/utility-server
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'utility-server:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  runPolicy: Serial
