apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-backups
  namespace: iankwatts-tools
spec:
  schedule: '*/5 * * * *'
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: github-backups-s3-creds-volume
              secret:
                secretName: github-backups-s3-creds
          containers:
            - name: github-backups
              image: >-
                image-registry.openshift-image-registry.svc:5000/iankwatts-tools/utility-server@sha256:4e471ab608e16c99b5879fc42512417c675c93ec8c6e4bc8c8d038e706a49bb5
              args:
                - /bin/sh
                - '-c'
                - /scripts/github_backup.sh
              volumeMounts:
                - name: github-backups-s3-creds-volume
                  mountPath: /etc/github-backups-s3-creds
                  readOnly: true
          restartPolicy: OnFailure

